version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      # - run: sudo apt update
      # - run: sudo apt install -y gmsh
      - run: pip install pytest pytest-cov excode --user
      - checkout
      # install gmsh from ppa
      - run: sudo apt-get install -y software-properties-common
      - run: sudo apt-add-repository -y ppa:nschloe/gmsh-backports
      - run: sudo apt update
      - run: sudo apt install -y gmsh
      # install
      - run: pip install . --user
      - run: pip install -r test_requirements.txt --user
      # The actual test
      - run: excode README.md test/readme_test.py --filter python,test
      - run:
          command: pytest --cov pygmsh
          working_directory: test/
          environment:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
